---
title: "ggplot"
format: html
editor: visual
---

```{r}
#| label: setup
#| echo: false
#| output: false
#| message: false
library(tidyverse)
library(ggpubr)
library(PxWebApiData)
library(readxl)
```

## Intro ggplot

```{r}
ggplot(
  data = mtcars, 
  mapping = aes(x = disp, y = mpg),
  ) + 
  geom_point() + 
  geom_smooth(level = 0.99) +
  geom_smooth(method = "lm", 
              colour = "red",
              se = FALSE
              )

```

```{r}
gg1 <-   ggplot(data = mtcars, mapping = aes(x = disp, y = mpg)) +
  geom_point()

```

```{r}
gg2 <-   ggplot(data = mtcars) +
  geom_point(mapping = aes(x = disp, y = mpg))

```

```{r}
ggarrange(gg1, gg2, labels = c("mapping = aes in ggplot", "mapping = aes in geom_*"),
          nrow = 2)
```

```{r}
ggplot() +
  geom_point(
    mapping = aes(x = disp, y = mpg,
                  shape = factor(cyl),
                  size = qsec,
                  alpha = wt,
                  colour = factor(am),
                  ),
    data = mtcars,
  )

 
```

```{r}
gg1 <- ggplot() +
  geom_point(data = mtcars,
             mapping = aes(
               x = disp, 
               y = mpg, 
               colour = factor(cyl), 
               alpha = 3.6*(0.25*1609.347)/qsec,
               shape = factor(ifelse(am, "Man", "Aut"))),
             size = 4) +
  labs(
    colour = "cyl",
    alpha = "speed\n(km/h)", 
    shape = "trans-\nmission"
    )
```

```{r}
gg1 + 
  geom_smooth(
      data = mtcars,
    mapping = aes(x = disp, y = mpg),
    span = 0.5,
    level = 0.99,
  ) +
geom_smooth(
    data = mtcars,
    mapping = aes(x = disp, y = mpg),
    span = 0.5,
    level = 0.95,
  ) +
geom_smooth(
  data = mtcars,
  mapping = aes(x = disp, y = mpg),
  method = "lm",
  se = FALSE,
  colour = "red",
)

```

```{r}
gg1 + 
  geom_smooth(
     data = mtcars,
    mapping = aes(x = disp, y = mpg),
    method = "lm",
    colour = "blue",
    se = FALSE,
  ) +
  #robust lm
  geom_smooth(
     data = mtcars,
    mapping = aes(x = disp, y = mpg),
    method = MASS::rlm,
    colour = "Red",
    SE = FALSE
  )
```

```{r}
ggplot(
  data = mtcars, 
  mapping = aes(
    x = disp, 
    y = mpg
    )
  ) +
  geom_point() +
  geom_smooth(
    method = "lm", 
    se = FALSE
    ) +
  # robust lm
  geom_smooth(
    method = MASS::rlm, 
    colour = 'Red', 
    se = FALSE
    )
```

```{r}
## create tibble from scratch
df_mean <-   tibble(
  cyl = c("avg. car 4 cyl.", "avg. car 6 cyl.", "avg. car 8 cyl."), 
  mpg = c(22.66, 17.74, 15.10), 
  disp = c(105.14, 183.31, 353.10)
  )
df_mean
```

```{r}
ggplot(
  data = mtcars, 
  mapping = aes(
    x = hp, 
    y = 1609.347/(2*qsec^2)
    )
  ) +
  facet_wrap(~cut_number(wt, n =3)) +
  geom_point(
    aes(colour = cut_number(
      wt, 
      n = 3)
      )
    ) +
  geom_smooth(
    method = "lm", 
    se = FALSE
    )
```

```{r}
ggplot(
  data = mtcars, 
  mapping = aes(x = disp, y = mpg)
  ) +
  geom_point(
    mapping = aes(colour = factor(cyl))
    ) +
  geom_smooth(
    method = "lm", 
    se = FALSE
    ) +
  geom_smooth(
    method = MASS::rlm, 
    colour = 'Red', 
    se = FALSE
    ) +
  geom_point(
    data = df_mean, 
    mapping = aes(x = disp, y = mpg), 
    colour = "black", 
    size = 3
    ) +
  geom_text(
    data = df_mean, 
    mapping = aes(x = disp, y = mpg, label = cyl), 
    colour = "black", 
    vjust = 1.5
    )
```

```{r}
#new dataframe to use for the grey points
hp_acc <- data.frame(
  hp = mtcars$hp, 
  acc = 1609.347/(2*mtcars$qsec^2)
  )

ggplot(
  data = mtcars, 
  mapping = aes(x = hp, y = 1609.347/(2*qsec^2))
  ) +
  geom_point(
    data = hp_acc, 
    mapping = aes(x = hp, y = acc), colour = "grey80"
    ) +
  facet_wrap(
    ~cut_number(
      wt, 
      n =3 , 
      labels = c("Light", "Medium", "Heavy")
      )
    ) +
  geom_point(
    mapping = aes(colour = cut_number(
      wt, 
      n = 3, 
      labels = c("Light", "Medium", "Heavy")
      )
      ),
    show.legend = TRUE
    ) +
  geom_smooth(
      mapping = aes(
      colour = cut_number(
        wt, 
        n = 3, 
        labels = c("Light", "Medium", "Heavy")
        )
      ),
    method = "lm", 
    se = FALSE
    ) +
  labs(
    y = "Mean acceleration (m/s^2)", 
    colour = "Weight"
    )


```

```{r}
ggplot(
  data = mtcars, 
  mapping = aes(x = hp, y = 1609.347/(2*qsec^2))
  ) +
  geom_point(
    data = hp_acc, 
    mapping = aes(x = hp, y = acc), 
    colour = "grey80"
    ) +
  facet_grid(
    factor(cyl)~cut_number(
      wt, 
      n =3 , 
      labels = c("Light", "Medium", "Heavy"))
    ) +
  geom_point(
    mapping = aes(
      colour = cut_number(
        wt, 
        n = 3, 
        labels = c("Light", "Medium", "Heavy")
        )
      ),
    show.legend = FALSE
    ) +
  geom_smooth(
    method = "lm", 
    se = FALSE
    ) +
  labs(
    y = "Mean acceleration", 
    colour = "Weight"
    )
```

```{r}
ggplot(
  data = mtcars, 
  mapping = aes(x = hp, y = 1609.347/(2*qsec^2))
  ) +
  geom_point(
    data = hp_acc, 
    mapping = aes(x = hp, y = acc), 
    colour = "grey80"
    ) +
  facet_grid(
    factor(cyl)~cut_number(
      wt, 
      n =3 , 
      labels = c("Light", "Medium", "Heavy"))
    ) +
  geom_point(
    mapping = aes(
      colour = cut_number(
        wt, 
        n = 3, 
        labels = c("Light", "Medium", "Heavy")
        )
      ),
    show.legend = FALSE
    ) +
  geom_smooth(
      mapping = aes(
      colour = cut_number(
        wt, 
        n = 3, 
        labels = c("Light", "Medium", "Heavy")
        )
      ),
    method = "lm", 
    se = FALSE
    ) +
  labs(
    y = "Mean acceleration", 
    colour = "Weight"
    )
```

```{r}
metadata_10540 <- ApiData(
  "http://data.ssb.no/api/v0/en/table/10540",
  returnMetaFrames = TRUE
  )
```

```{r}
library(readxl)
X10540_20230908_104609 <- read_excel("10540_20230908-104609.xlsx", 
    sheet = "RegHeltLedige", skip = 2)
view(X10540_20230908_104609)
```

```{r}
library(readr)
X10540_20230908_113214 <- read_delim(
  "10540_20230908-113214.csv", 
    delim = ";",
  escape_double = FALSE, 
  locale = locale(date_names = "nb", 
        encoding = "ISO-8859-1"), 
  trim_ws = TRUE, 
    skip = 1,
  show_col_types = FALSE,
  )
```

```{r}
metadata_10540 <- ApiData(
  "http://data.ssb.no/api/v0/en/table/10540",
  returnMetaFrames = TRUE
  )
```

```{r}
library(PxWebApiData)
metadata_13891 <- ApiData(
  "https://data.ssb.no/api/v0/no/table/13891/",
  returnMetaFrames = TRUE
  )
```

```{r}
#Get more info about table
ApiData(
"http://data.ssb.no/api/v0/en/table/10540",
returnApiQuery = TRUE
) 
```

```{r}
unemp99to02 <- ApiData12(
  "http://data.ssb.no/api/v0/en/table/10540",
  # Have not been able to specify more complex regions
  Region = list("11*"),
  Tid = c(paste(
    rep(1999:2002, each = 12), 
    "M",
    sprintf("%02d", 1:12), 
    sep = "")
    )
  )

```

```{r}
metadata_10540$Tid
```

```{r}
paste(
  rep(1999:2002, each = 12),
  "M",
  sprintf("%02d", 1:12),
  sep = ""
)

```
